### ISSUE TITLE
Mosquitoes

### ISSUE THREAD

**Issue by kaihendry** [hackerspacesg/admin#7]

**Comment by robertsky** [comment]
Here is an update on mozzies in the space. The last time that mozzies was found in the space, it was due to clogged drainage or pipes just outside KGB, and NEA had kindly cleared the drainage/pipes up. But that does not mean that mozzies might not be breeding in HSG.

Do ensure that any pails or containers in the toilets and sink area are free of water. Empty them if you see water pooling in such containers, or turn over them to prevent water from being stored. 

![image](https://cloud.githubusercontent.com/assets/1820367/6770652/9060c018-d101-11e4-9bc5-dd4542ca4c39.png)

image taken from: http://www.dengue.gov.sg/subject.asp?id=100

**Comment by rolandturner** [comment]
Related: I'm not in the space often enough to keep this done, but I'd 
suggest that if you see the mosquito trap light off (it seems to turn 
itself off a frequently; I don't know why), touch the top of it to turn 
it on. It is true that the device's approach to trapping them is a 
little probabilistic, but that probability drops to zero when it's off.
- Roland

**Comment by hyperair** [comment]
I think it's a non-issue these days. Close?
